// <auto-generated />
using System;
using Booksy.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booksy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250928183900_NewReviews")]
    partial class NewReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booksy.Models.Entities.Books.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Author of Harry Potter",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 480, DateTimeKind.Utc).AddTicks(3779),
                            IsDeleted = false,
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Author of Game of Thrones",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 480, DateTimeKind.Utc).AddTicks(5085),
                            IsDeleted = false,
                            Name = "George R.R. Martin"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Author of The Lord of the Rings",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 480, DateTimeKind.Utc).AddTicks(5089),
                            IsDeleted = false,
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Famous mystery writer",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 480, DateTimeKind.Utc).AddTicks(5091),
                            IsDeleted = false,
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Horror and thriller author",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 480, DateTimeKind.Utc).AddTicks(5101),
                            IsDeleted = false,
                            Name = "Stephen King"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Author of Da Vinci Code",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 480, DateTimeKind.Utc).AddTicks(5113),
                            IsDeleted = false,
                            Name = "Dan Brown"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Author of Hunger Games",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 480, DateTimeKind.Utc).AddTicks(5115),
                            IsDeleted = false,
                            Name = "Suzanne Collins"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "American novelist",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 480, DateTimeKind.Utc).AddTicks(5118),
                            IsDeleted = false,
                            Name = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Famous American writer",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 480, DateTimeKind.Utc).AddTicks(5120),
                            IsDeleted = false,
                            Name = "Mark Twain"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Science fiction author",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 480, DateTimeKind.Utc).AddTicks(5125),
                            IsDeleted = false,
                            Name = "Isaac Asimov"
                        });
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Traffic")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PromotionId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(4350),
                            Discount = 0m,
                            ISBN = "9780747532699",
                            IsDeleted = false,
                            Price = 19.99m,
                            Quantity = 0,
                            Stock = 50,
                            Title = "Harry Potter and the Philosopher's Stone",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8791),
                            Discount = 0m,
                            ISBN = "9780747538493",
                            IsDeleted = false,
                            Price = 19.99m,
                            Quantity = 0,
                            Stock = 45,
                            Title = "Harry Potter and the Chamber of Secrets",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8802),
                            Discount = 0m,
                            ISBN = "9780553103540",
                            IsDeleted = false,
                            Price = 24.99m,
                            Quantity = 0,
                            Stock = 40,
                            Title = "A Game of Thrones",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8807),
                            Discount = 0m,
                            ISBN = "9780553108033",
                            IsDeleted = false,
                            Price = 24.99m,
                            Quantity = 0,
                            Stock = 35,
                            Title = "A Clash of Kings",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8811),
                            Discount = 0m,
                            ISBN = "9780385121675",
                            IsDeleted = false,
                            Price = 17.99m,
                            Quantity = 0,
                            Stock = 30,
                            Title = "The Shining",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8871),
                            Discount = 0m,
                            ISBN = "9780450411434",
                            IsDeleted = false,
                            Price = 18.99m,
                            Quantity = 0,
                            Stock = 25,
                            Title = "It",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8879),
                            Discount = 0m,
                            ISBN = "9780547928210",
                            IsDeleted = false,
                            Price = 22.99m,
                            Quantity = 0,
                            Stock = 40,
                            Title = "The Lord of the Rings: Fellowship",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8883),
                            Discount = 0m,
                            ISBN = "9780062073501",
                            IsDeleted = false,
                            Price = 14.99m,
                            Quantity = 0,
                            Stock = 30,
                            Title = "Murder on the Orient Express",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 6,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8888),
                            Discount = 0m,
                            ISBN = "9780307474278",
                            IsDeleted = false,
                            Price = 16.99m,
                            Quantity = 0,
                            Stock = 25,
                            Title = "The Da Vinci Code",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 7,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8898),
                            Discount = 0m,
                            ISBN = "9780439023481",
                            IsDeleted = false,
                            Price = 18.99m,
                            Quantity = 0,
                            Stock = 35,
                            Title = "The Hunger Games",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 7,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8902),
                            Discount = 0m,
                            ISBN = "9780439023498",
                            IsDeleted = false,
                            Price = 18.99m,
                            Quantity = 0,
                            Stock = 35,
                            Title = "Catching Fire",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 7,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8905),
                            Discount = 0m,
                            ISBN = "9780439023511",
                            IsDeleted = false,
                            Price = 18.99m,
                            Quantity = 0,
                            Stock = 35,
                            Title = "Mockingjay",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 10,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8908),
                            Discount = 0m,
                            ISBN = "9780553293357",
                            IsDeleted = false,
                            Price = 15.99m,
                            Quantity = 0,
                            Stock = 25,
                            Title = "Foundation",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 10,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8912),
                            Discount = 0m,
                            ISBN = "9780553294385",
                            IsDeleted = false,
                            Price = 15.99m,
                            Quantity = 0,
                            Stock = 25,
                            Title = "I, Robot",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8915),
                            Discount = 0m,
                            ISBN = "9780684801223",
                            IsDeleted = false,
                            Price = 12.99m,
                            Quantity = 0,
                            Stock = 20,
                            Title = "The Old Man and The Sea",
                            Traffic = 0
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 482, DateTimeKind.Utc).AddTicks(8919),
                            Discount = 0m,
                            ISBN = "9780486280615",
                            IsDeleted = false,
                            Price = 11.99m,
                            Quantity = 0,
                            Stock = 20,
                            Title = "Adventures of Huckleberry Finn",
                            Traffic = 0
                        });
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(3249),
                            IsDeleted = false,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(4956),
                            IsDeleted = false,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(4961),
                            IsDeleted = false,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(4964),
                            IsDeleted = false,
                            Name = "Children"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(4967),
                            IsDeleted = false,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(4985),
                            IsDeleted = false,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(4988),
                            IsDeleted = false,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(4991),
                            IsDeleted = false,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(4993),
                            IsDeleted = false,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(4998),
                            IsDeleted = false,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(5017),
                            IsDeleted = false,
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(5018),
                            IsDeleted = false,
                            Name = "History"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(5020),
                            IsDeleted = false,
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 479, DateTimeKind.Utc).AddTicks(5021),
                            IsDeleted = false,
                            Name = "Science Fiction"
                        });
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Comment = "Loved this book!",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 483, DateTimeKind.Utc).AddTicks(7753),
                            IsDeleted = false,
                            Rating = 5,
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            Comment = "Great story.",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 484, DateTimeKind.Utc).AddTicks(1097),
                            IsDeleted = false,
                            Rating = 4,
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 5,
                            Comment = "Terrifying but amazing.",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 484, DateTimeKind.Utc).AddTicks(1104),
                            IsDeleted = false,
                            Rating = 5,
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 10,
                            Comment = "Could not put it down!",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 484, DateTimeKind.Utc).AddTicks(1107),
                            IsDeleted = false,
                            Rating = 5,
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 7,
                            Comment = "Classic fantasy!",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 484, DateTimeKind.Utc).AddTicks(1108),
                            IsDeleted = false,
                            Rating = 5,
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 13,
                            Comment = "Interesting sci-fi.",
                            CreatedAt = new DateTime(2025, 9, 28, 18, 38, 58, 484, DateTimeKind.Utc).AddTicks(1120),
                            IsDeleted = false,
                            Rating = 4,
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000003"
                        });
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CarrierTrackingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("PromotionId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f6d24adb-6318-4e4c-b290-7e49e08a6010",
                            Email = "admin@booksy.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "System Admin",
                            NormalizedEmail = "ADMIN@BOOKSY.COM",
                            NormalizedUserName = "ADMIN@BOOKSY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKu41fO8q6swgXSU5GrjkCqoSgqxqJ/gVQ+S0gFjs7XWbgGTpsooLH2rDIXg98QQ3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a37c47c8-e9d2-4133-8ab6-521948b9fca5",
                            TwoFactorEnabled = false,
                            UserName = "admin@booksy.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cd3086b3-95d0-4ef7-8b6b-69a1b0aab96d",
                            Email = "customer1@booksy.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Alice",
                            NormalizedEmail = "CUSTOMER1@BOOKSY.COM",
                            NormalizedUserName = "CUSTOMER1@BOOKSY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF35fCepg9Arj+h5nCxruC02n7vBgoE7XB+BUnnE2tbUbEudFY1630/qEX5+9FUOxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1da4277a-c6cd-4c8d-8cff-6ebecde49f67",
                            TwoFactorEnabled = false,
                            UserName = "customer1@booksy.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f6c58d32-f5c4-4211-9a81-4f39311bf6bf",
                            Email = "customer2@booksy.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Bob",
                            NormalizedEmail = "CUSTOMER2@BOOKSY.COM",
                            NormalizedUserName = "CUSTOMER2@BOOKSY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEExarm+MDvrSNQca0r/ql4lHra+Xc5XmrH5tRIA4XnTVqC/vemUCvROKGMR5DUxk7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "06e40e00-6548-4be2-9b12-c6ab6edd8b2d",
                            TwoFactorEnabled = false,
                            UserName = "customer2@booksy.com"
                        });
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CartId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.UserOTP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OTPNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserOTPs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Book", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Books.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Promotions.Promotion", null)
                        .WithMany("Books")
                        .HasForeignKey("PromotionId");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Review", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.Order", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.OrderItem", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Book", "Book")
                        .WithMany("OrderItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.Shipment", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Orders.Order", "Order")
                        .WithOne("Shipment")
                        .HasForeignKey("Booksy.Models.Entities.Orders.Shipment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Coupon", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Promotions.Promotion", "Promotion")
                        .WithMany("Coupons")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Discount", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.HasOne("Booksy.Models.Entities.Promotions.Promotion", "Promotion")
                        .WithMany("Discounts")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.Cart", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.CartItem", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Users.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.UserOTP", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Book", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Promotion", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Coupons");

                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.ApplicationUser", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
