// <auto-generated />
using System;
using Booksy.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Booksy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookTag", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTag");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Author_IsDeleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Author_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Author_Slug");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Bio = "Author of Harry Potter series",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 712, DateTimeKind.Utc).AddTicks(5682),
                            IsDeleted = false,
                            Name = "J.K. Rowling",
                            Slug = "jk-rowling"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Bio = "Author of Game of Thrones series",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 712, DateTimeKind.Utc).AddTicks(7289),
                            IsDeleted = false,
                            Name = "George R.R. Martin",
                            Slug = "george-rr-martin"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Bio = "Author of The Lord of the Rings",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 712, DateTimeKind.Utc).AddTicks(7538),
                            IsDeleted = false,
                            Name = "J.R.R. Tolkien",
                            Slug = "jrr-tolkien"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Bio = "Famous mystery and crime writer",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 712, DateTimeKind.Utc).AddTicks(7699),
                            IsDeleted = false,
                            Name = "Agatha Christie",
                            Slug = "agatha-christie"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Bio = "Renowned horror and thriller author",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 712, DateTimeKind.Utc).AddTicks(7875),
                            IsDeleted = false,
                            Name = "Stephen King",
                            Slug = "stephen-king"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Bio = "Author of The Da Vinci Code and Robert Langdon series",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 712, DateTimeKind.Utc).AddTicks(8028),
                            IsDeleted = false,
                            Name = "Dan Brown",
                            Slug = "dan-brown"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Bio = "Author of The Hunger Games trilogy",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 712, DateTimeKind.Utc).AddTicks(8170),
                            IsDeleted = false,
                            Name = "Suzanne Collins",
                            Slug = "suzanne-collins"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Bio = "American novelist and Nobel Prize winner",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 712, DateTimeKind.Utc).AddTicks(8318),
                            IsDeleted = false,
                            Name = "Ernest Hemingway",
                            Slug = "ernest-hemingway"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Bio = "American writer and humorist",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 712, DateTimeKind.Utc).AddTicks(9691),
                            IsDeleted = false,
                            Name = "Mark Twain",
                            Slug = "mark-twain"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Bio = "Science fiction and non-fiction author",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 712, DateTimeKind.Utc).AddTicks(9892),
                            IsDeleted = false,
                            Name = "Isaac Asimov",
                            Slug = "isaac-asimov"
                        });
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Traffic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_Book_AuthorId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Book_CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasDatabaseName("IX_Book_ISBN");

                    b.HasIndex("PromotionId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Book_Slug");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Book_Title");

                    b.HasIndex("CategoryId", "IsDeleted")
                        .HasDatabaseName("IX_Book_CategoryId_IsDeleted");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 714, DateTimeKind.Utc).AddTicks(7450),
                            Discount = 0m,
                            ISBN = "9780747532699",
                            IsDeleted = false,
                            Price = 19.99m,
                            Quantity = 0,
                            Slug = "harry-potter-and-the-philosophers-stone",
                            Stock = 50,
                            Title = "Harry Potter and the Philosopher's Stone",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(91),
                            Discount = 0m,
                            ISBN = "9780747538493",
                            IsDeleted = false,
                            Price = 19.99m,
                            Quantity = 0,
                            Slug = "harry-potter-and-the-chamber-of-secrets",
                            Stock = 45,
                            Title = "Harry Potter and the Chamber of Secrets",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(328),
                            Discount = 0m,
                            ISBN = "9780553103540",
                            IsDeleted = false,
                            Price = 24.99m,
                            Quantity = 0,
                            Slug = "a-game-of-thrones",
                            Stock = 40,
                            Title = "A Game of Thrones",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(487),
                            Discount = 0m,
                            ISBN = "9780553108033",
                            IsDeleted = false,
                            Price = 24.99m,
                            Quantity = 0,
                            Slug = "a-clash-of-kings",
                            Stock = 35,
                            Title = "A Clash of Kings",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(641),
                            Discount = 0m,
                            ISBN = "9780385121675",
                            IsDeleted = false,
                            Price = 17.99m,
                            Quantity = 0,
                            Slug = "the-shining",
                            Stock = 30,
                            Title = "The Shining",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(818),
                            Discount = 0m,
                            ISBN = "9780450411434",
                            IsDeleted = false,
                            Price = 18.99m,
                            Quantity = 0,
                            Slug = "it",
                            Stock = 25,
                            Title = "It",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(957),
                            Discount = 0m,
                            ISBN = "9780547928210",
                            IsDeleted = false,
                            Price = 22.99m,
                            Quantity = 0,
                            Slug = "the-lord-of-the-rings-fellowship",
                            Stock = 40,
                            Title = "The Lord of the Rings: Fellowship",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(1130),
                            Discount = 0m,
                            ISBN = "9780062073501",
                            IsDeleted = false,
                            Price = 14.99m,
                            Quantity = 0,
                            Slug = "murder-on-the-orient-express",
                            Stock = 30,
                            Title = "Murder on the Orient Express",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(1291),
                            Discount = 0m,
                            ISBN = "9780307474278",
                            IsDeleted = false,
                            Price = 16.99m,
                            Quantity = 0,
                            Slug = "the-da-vinci-code",
                            Stock = 25,
                            Title = "The Da Vinci Code",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(1447),
                            Discount = 0m,
                            ISBN = "9780439023481",
                            IsDeleted = false,
                            Price = 18.99m,
                            Quantity = 0,
                            Slug = "the-hunger-games",
                            Stock = 35,
                            Title = "The Hunger Games",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(1598),
                            Discount = 0m,
                            ISBN = "9780439023498",
                            IsDeleted = false,
                            Price = 18.99m,
                            Quantity = 0,
                            Slug = "catching-fire",
                            Stock = 35,
                            Title = "Catching Fire",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(1742),
                            Discount = 0m,
                            ISBN = "9780439023511",
                            IsDeleted = false,
                            Price = 18.99m,
                            Quantity = 0,
                            Slug = "mockingjay",
                            Stock = 35,
                            Title = "Mockingjay",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(1877),
                            Discount = 0m,
                            ISBN = "9780553293357",
                            IsDeleted = false,
                            Price = 15.99m,
                            Quantity = 0,
                            Slug = "foundation",
                            Stock = 25,
                            Title = "Foundation",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(2012),
                            Discount = 0m,
                            ISBN = "9780553294385",
                            IsDeleted = false,
                            Price = 15.99m,
                            Quantity = 0,
                            Slug = "i-robot",
                            Stock = 25,
                            Title = "I, Robot",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000008"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(2162),
                            Discount = 0m,
                            ISBN = "9780684801223",
                            IsDeleted = false,
                            Price = 12.99m,
                            Quantity = 0,
                            Slug = "the-old-man-and-the-sea",
                            Stock = 20,
                            Title = "The Old Man and The Sea",
                            Traffic = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            AuthorId = new Guid("20000000-0000-0000-0000-000000000009"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(2323),
                            Discount = 0m,
                            ISBN = "9780486280615",
                            IsDeleted = false,
                            Price = 11.99m,
                            Quantity = 0,
                            Slug = "adventures-of-huckleberry-finn",
                            Stock = 20,
                            Title = "Adventures of Huckleberry Finn",
                            Traffic = 0
                        });
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Category_IsDeleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Category_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Category_Slug");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 700, DateTimeKind.Utc).AddTicks(4472),
                            IsDeleted = false,
                            Name = "Fiction",
                            Slug = "fiction"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 710, DateTimeKind.Utc).AddTicks(9737),
                            IsDeleted = false,
                            Name = "Non-Fiction",
                            Slug = "non-fiction"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(5412),
                            IsDeleted = false,
                            Name = "Science",
                            Slug = "science"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(5607),
                            IsDeleted = false,
                            Name = "Children",
                            Slug = "children"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(5750),
                            IsDeleted = false,
                            Name = "Fantasy",
                            Slug = "fantasy"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(5901),
                            IsDeleted = false,
                            Name = "Mystery",
                            Slug = "mystery"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(6036),
                            IsDeleted = false,
                            Name = "Thriller",
                            Slug = "thriller"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(6167),
                            IsDeleted = false,
                            Name = "Romance",
                            Slug = "romance"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(6299),
                            IsDeleted = false,
                            Name = "Horror",
                            Slug = "horror"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(6553),
                            IsDeleted = false,
                            Name = "Biography",
                            Slug = "biography"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(6715),
                            IsDeleted = false,
                            Name = "Self-Help",
                            Slug = "self-help"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(7449),
                            IsDeleted = false,
                            Name = "History",
                            Slug = "history"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(7629),
                            IsDeleted = false,
                            Name = "Poetry",
                            Slug = "poetry"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 711, DateTimeKind.Utc).AddTicks(7777),
                            IsDeleted = false,
                            Name = "Science Fiction",
                            Slug = "science-fiction"
                        });
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_Review_BookId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Review_IsDeleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Review_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Review_UserId");

                    b.HasIndex("BookId", "Status")
                        .HasDatabaseName("IX_Review_BookId_Status");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            BookId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Comment = "Absolutely loved this book! A must-read for everyone.",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 715, DateTimeKind.Utc).AddTicks(9003),
                            IsDeleted = false,
                            Rating = 5,
                            ReviewerName = "Alice",
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            BookId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Comment = "Great story and world-building, though a bit lengthy.",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 716, DateTimeKind.Utc).AddTicks(469),
                            IsDeleted = false,
                            Rating = 4,
                            ReviewerName = "Bob",
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            BookId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Comment = "Terrifying but amazing. Couldn't put it down!",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 716, DateTimeKind.Utc).AddTicks(592),
                            IsDeleted = false,
                            Rating = 5,
                            ReviewerName = "Alice",
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            BookId = new Guid("30000000-0000-0000-0000-000000000010"),
                            Comment = "The most thrilling read I've had all year!",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 716, DateTimeKind.Utc).AddTicks(713),
                            IsDeleted = false,
                            Rating = 5,
                            ReviewerName = "Bob",
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            BookId = new Guid("30000000-0000-0000-0000-000000000007"),
                            Comment = "Classic fantasy at its finest!",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 716, DateTimeKind.Utc).AddTicks(833),
                            IsDeleted = false,
                            Rating = 5,
                            ReviewerName = "Alice",
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            BookId = new Guid("30000000-0000-0000-0000-000000000013"),
                            Comment = "Interesting sci-fi concepts, great foundation for thought.",
                            CreatedAt = new DateTime(2026, 7, 12, 14, 50, 7, 716, DateTimeKind.Utc).AddTicks(958),
                            IsDeleted = false,
                            Rating = 4,
                            ReviewerName = "Bob",
                            Status = 1,
                            UserId = "00000000-0000-0000-0000-000000000003"
                        });
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Tag_IsDeleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Tag_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Tag_Slug");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CarrierTrackingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ShippedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("PromotionId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ReceiveNewsletter")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ThemePreference")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "90f186ef-c477-4e95-b023-317b04cd3edf",
                            Email = "admin@booksy.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            Name = "System Admin",
                            NormalizedEmail = "ADMIN@BOOKSY.COM",
                            NormalizedUserName = "ADMIN@BOOKSY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEVgao+rr+oOcRFsCn55hmn7j8Fa2FFb9r3DTfud1rrar1BHmYQon9fFxUxJxhq3OQ==",
                            PhoneNumberConfirmed = false,
                            PreferredLanguage = "en",
                            ReceiveNewsletter = true,
                            RegisteredDate = new DateTime(2026, 7, 12, 14, 50, 7, 500, DateTimeKind.Utc).AddTicks(3385),
                            SecurityStamp = "275b7daa-8c8b-43a9-94d9-043f1aace741",
                            TwoFactorEnabled = false,
                            UserName = "admin@booksy.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "49d646bf-2275-4d15-9d5c-03d8bcb0e7eb",
                            Email = "customer1@booksy.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            Name = "Alice",
                            NormalizedEmail = "CUSTOMER1@BOOKSY.COM",
                            NormalizedUserName = "CUSTOMER1@BOOKSY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGX1chMx09mvGzjjv63uuKpSCEblvHVWPCYYSoFkDO7pYyyeAcjtYoeFAF3jhN9LvA==",
                            PhoneNumberConfirmed = false,
                            PreferredLanguage = "en",
                            ReceiveNewsletter = true,
                            RegisteredDate = new DateTime(2026, 7, 12, 14, 50, 7, 584, DateTimeKind.Utc).AddTicks(1851),
                            SecurityStamp = "9a8526b7-d393-4c6b-9128-281f1fc63a04",
                            TwoFactorEnabled = false,
                            UserName = "customer1@booksy.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7fc5cf2c-6ec9-416a-bc2a-bc7eb416897d",
                            Email = "customer2@booksy.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            Name = "Bob",
                            NormalizedEmail = "CUSTOMER2@BOOKSY.COM",
                            NormalizedUserName = "CUSTOMER2@BOOKSY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGCxftyP1AT4ikTIDY+Ei6zx7m1RSyor8OoxMIhlXGd8QISaCk+Xi0jFs0nHHxRFaA==",
                            PhoneNumberConfirmed = false,
                            PreferredLanguage = "en",
                            ReceiveNewsletter = true,
                            RegisteredDate = new DateTime(2026, 7, 12, 14, 50, 7, 641, DateTimeKind.Utc).AddTicks(5815),
                            SecurityStamp = "7b8647b0-665b-455c-add5-41cc826d1457",
                            TwoFactorEnabled = false,
                            UserName = "customer2@booksy.com"
                        });
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CartId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CartId1");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.UserOTP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OTPNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserOTPs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookTag", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Books.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Book", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Books.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Promotions.Promotion", null)
                        .WithMany("Books")
                        .HasForeignKey("PromotionId");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Review", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.Order", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.OrderItem", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Book", "Book")
                        .WithMany("OrderItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.Shipment", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Orders.Order", "Order")
                        .WithOne("Shipment")
                        .HasForeignKey("Booksy.Models.Entities.Orders.Shipment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Coupon", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Promotions.Promotion", "Promotion")
                        .WithMany("Coupons")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Discount", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.HasOne("Booksy.Models.Entities.Promotions.Promotion", "Promotion")
                        .WithMany("Discounts")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.Cart", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.CartItem", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Books.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Users.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.UserOTP", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Booksy.Models.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Book", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Books.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Promotions.Promotion", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Coupons");

                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.ApplicationUser", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Booksy.Models.Entities.Users.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
